trigger:
  - master

pr:
  - master

jobs:
  - job: build
    strategy:
      matrix:
        win:
          imageName: 'windows-2019'
          pass: 'A4_bg3dVd'
          userName: 'DeskGapUser'

    pool:
      vmImage: $(imageName)

    steps:
    - script: |
        choco install -y pstools
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        cl isadmin.cpp
    - powershell: |
        $securePass = ConvertTo-SecureString $env:pass -AsPlainText -Force
        New-LocalUser $env:userName -Password $securePass -FullName $env:userName

        $Acl = Get-ACL .
        $AccessRule= New-Object System.Security.AccessControl.FileSystemAccessRule($env:userName,"FullControl","ContainerInherit,Objectinherit","none","Allow")      
        $Acl.AddAccessRule($AccessRule)
        Set-Acl . $Acl
    - script: |
        .\isadmin.exe
        echo %userName% %pass% %cd%
        psexec -accepteula -u %userName% -p %pass% -w %cd% cmd /c "isadmin.exe > isadmin_out 2>&1"
        type isadmin_out
