trigger:
  - master

pr:
  - master

jobs:
  - job: build
    strategy:
      matrix:
        win:
          imageName: 'windows-2019'
          cmakeGenerator: 'Visual Studio 16 2019'
          buildDistPath: 'build/Release'
    pool:
      vmImage: $(imageName)

    steps:
    - powershell: |
        echo $env:UserName
        $pass = "A4%_b*g3dV"
        $userName = "DeskGapUser"

        $securePass = ConvertTo-SecureString $pass -AsPlainText -Force
        New-LocalUser $userName -Password $securePass -FullName $userName
        Add-LocalGroupMember -Group "Remote Management Users" -Member $userName

        winrm quickconfig -quiet
        pushd WSMan:\localhost\Shell 
        set-item MaxConcurrentUsers 100 
        set-item MaxProcessesPerShell 10000 
        set-item MaxMemoryPerShellMB 1024 
        set-item MaxShellsPerUser 1000 
        pushd WSMan:\localhost\Plugin\microsoft.powershell\Quotas 
        set-item MaxConcurrentUsers 100 
        set-item MaxProcessesPerShell 10000 
        set-item MaxShells 1000 
        set-item MaxShellsPerUser 1000 
        restart-service winrm
        popd
        popd

        Get-Process | Out-File -FilePath Process.txt

        $Acl = Get-ACL .
        $AccessRule= New-Object System.Security.AccessControl.FileSystemAccessRule("everyone","FullControl","ContainerInherit,Objectinherit","none","Allow")      
        $Acl.AddAccessRule($AccessRule)
        Set-Acl . $Acl


        $cred =  New-Object -TypeName PSCredential -ArgumentList $userName, $securePass

        $remoteSession = new-pssession -computername localhost -Credential $cred
        Invoke-Command -Session $remoteSession -ScriptBlock {
          Set-Location $using:pwd
          Get-Location
          Get-Content Process.txt
        }
        $remoteLastExitCode = Invoke-Command -ScriptBlock { $lastexitcode } -Session $remoteSession

        exit $remoteLastExitCode