trigger:
  - master

pr:
  - master

jobs:
  - job: build
    strategy:
      matrix:
        win:
          imageName: 'windows-2019'
          cmakeGenerator: 'Visual Studio 16 2019'
          buildDistPath: 'build/Release'
    pool:
      vmImage: $(imageName)

    steps:
    - powershell: |
        echo $env:UserName
        $pass = "A4%_b*g3dV"
        $userName = $env:UserName

        $securePass = ConvertTo-SecureString $pass -AsPlainText -Force


        $UserAccount = Get-LocalUser -Name $userName
        $UserAccount | Set-LocalUser -Password $securePass

        $cred =  New-Object -TypeName PSCredential -ArgumentList $userName, $securePass

        winrm quickconfig -quiet

        Invoke-Command -ComputerName 'localhost' -Credential $cred -ScriptBlock { & cmd /c echo haha }

        $remoteSession = new-pssession -computername localhost
        Invoke-Command -Session $remoteSession -Credential $cred -ScriptBlock { & cmd /c "echo 1231 && exit 21" }
        $remoteLastExitCode = Invoke-Command -ScriptBlock { $lastexitcode } -Session $remoteSession

        echo $remoteLastExitCode