trigger:
  - master

pr:
  - master

jobs:
  - job: build
    strategy:
      matrix:
        win:
          imageName: 'windows-2019'
          cmakeGenerator: 'Visual Studio 16 2019'
          buildDistPath: 'build/Release'
    pool:
      vmImage: $(imageName)

    steps:
    - powershell: |
        net localgroup /add WinRMRemoteWMIUsers__

        $Acl = Get-ACL .
        $AccessRule= New-Object System.Security.AccessControl.FileSystemAccessRule("everyone","FullControl","ContainerInherit,Objectinherit","none","Allow")      
        $Acl.AddAccessRule($AccessRule)
        Set-Acl . $Acl
        
        $pass = "A4%_b*g3dV"
        $userName = "DeskGapUser"

        $securePass = ConvertTo-SecureString $pass -AsPlainText -Force
        New-LocalUser $userName -Password $securePass -FullName $userName
        Add-LocalGroupMember -Group "Remote Management Users" -Member $userName
        Add-LocalGroupMember -Group "WinRMRemoteWMIUsers__" -Member $userName

        Get-Process | Out-File -FilePath Process.txt

        $cred =  New-Object -TypeName PSCredential -ArgumentList $userName, $securePass
        
        $session = new-pssession -Credential $cred
        Invoke-Command -Session $session -ScriptBlock {
            Set-Location $using:pwd
            Get-Content Process.txt
        }
        $remoteLastExitCode = Invoke-Command -ScriptBlock { $lastexitcode } -Session $session
        exit $remoteLastExitCode
