trigger:
  - master

pr:
  - master

jobs:
  - job: build
    strategy:
      matrix:
        win:
          imageName: 'windows-2019'
          cmakeGenerator: 'Visual Studio 16 2019'
          buildDistPath: 'build/Release'
    pool:
      vmImage: $(imageName)

    steps:
    - powershell: |
        cl isadmin.cpp
        choco install -y pstools

        $Acl = Get-ACL .
        $AccessRule= New-Object System.Security.AccessControl.FileSystemAccessRule("everyone","FullControl","ContainerInherit,Objectinherit","none","Allow")      
        $Acl.AddAccessRule($AccessRule)
        Set-Acl . $Acl
        
        $pass = "A4%_b*g3dV"
        $userName = "DeskGapUser"

        $securePass = ConvertTo-SecureString $pass -AsPlainText -Force
        New-LocalUser $userName -Password $securePass -FullName $userName

        isadmin.exe
        psexec -u $userName -p $pass cmd /c "isadmin.exe > isadmin_out 2>&1"
        Get-Content isadmin_out


